[build]
  command = "npm run build"
  publish = "dist"
  
[dev]
  command = "npm run dev"
  port = 5173
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NETLIFY_SITE_ID = "63911bcb-ccd9-463b-aad0-57591e20376c"